### PR TITLE
Fix #664 - track added actions and only emit ai-reaction action if feature is used

### LINKED ISSUE #664: Codex fails to start github MCP
```
2025-09-10T17:54:44.855487Z ERROR codex_core::codex: MCP client for `github` failed to start: missing field `user_agent`
[2025-09-10T17:54:44] ERROR: MCP client for `github` failed to start: missing field `user_agent`
```

https://github.com/githubnext/gh-aw/actions/runs/17622421035/job/50070992826

### PR DESCRIPTION
**Pull request by dsyme**
Fixes: https://github.com/githubnext/gh-aw-internal/issues/664

Add is now clean:

```
Initialized empty Git repository in /home/dsyme/tmp/.git/
dsyme@DSYME-LAPDOG:~/tmp$ ../gh-aw/gh-aw add -r githubnext/agentics weekly-research
Package githubnext/agentics already exists. Updating...
Successfully installed package: githubnext/agentics
Added workflow: /home/dsyme/tmp/.github/workflows/weekly-research.md
✓ .github/workflows/weekly-research.md
dsyme@DSYME-LAPDOG:~/tmp$ git status
On branch master

No commits yet

Changes to be committed:
  (use "git rm --cached <file>..." to unstage)
        new file:   .gitattributes
        new file:   .github/workflows/agentics/shared/gh-extra-tools.md
        new file:   .github/workflows/agentics/shared/include-link.md
        new file:   .github/workflows/agentics/shared/job-summary.md
        new file:   .github/workflows/agentics/shared/tool-refused.md
        new file:   .github/workflows/agentics/shared/xpia.md
        new file:   .github/workflows/weekly-research.lock.yml
        new file:   .github/workflows/weekly-research.md
```

### CODE REVIEW

File: pkg/workflow/compiler.go [hunk 1]
```diff
@@ -90,6 +92,16 @@ func (c *Compiler) SetSkipValidation(skip bool) {
 	c.skipValidation = skip
 }
 
+// GetCreatedFiles returns the list of files created during compilation
+func (c *Compiler) GetCreatedFiles() []string {
+	return c.createdFiles
+}
+
+// ClearCreatedFiles clears the list of created files (useful for multiple compilations)
+func (c *Compiler) ClearCreatedFiles() {
```
Comment (dsyme) [inline pkg/workflow/compiler.go]: We shouldn't need the `GetCreatedFiles` and `createdFiles` for the compiler and should instead push the file tracker down into the compiler
